agent: "DQN"
env_name: "MiniGrid"
env_id: "MiniGrid-Empty-5x5-v0"
RGBImgPartialObsWrapper: False
ImgObsWrapper: False
vectorize: "Dummy_MiniGrid"
policy: "Basic_Q_network"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128,]
q_hidden_size: [128,]
activation: 'relu'


seed: 79811
parallels: 10
buffer_size: 100000
batch_size: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.5



start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 10000
sync_frequency: 50
training_frequency: 1
running_steps:  100000  # 200k
start_training: 1000



use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 1000
test_episode: 5
log_dir: "./logs/dqn/"
model_dir: "./models/dqn/"
